stages:
  - test
  - build
  - deploy

# Variables
variables:
  # Namens
  API_IMAGE: express-api
  WEB_IMAGE: next-app
  SPA_IMAGE: react-spa

# Vitest
test_all:
  stage: test
  tags:
    - vps-deploy
  # image: node:24-alpine
  script:
    # Full clearing
    - docker rm -f test_db || true
    - docker network rm test_net || true
    # - rm -rf node_modules package-lock.json
    # network for DB
    - docker network create test_net || true
    - mkdir -p .npm-cache
    # Temporary DB for tests
    - |
      docker run -d --name test_db \
        --network test_net \
        -e POSTGRES_PASSWORD=pass \
        -e POSTGRES_DB=test_db \
        postgres:15-alpine
    - sleep 10
    # Tests
    - |
      docker run --rm --network test_net \
      --user $(id -u):$(id -g) \
      -v "$(pwd)":/app -w /app \
      -e DATABASE_URL="postgresql://postgres:pass@test_db:5432/test_db" \
      -e NPM_CONFIG_CACHE=/app/.npm-cache \
      node:24-alpine \
      sh -c "npm install && npx prisma generate --schema=packages/database/schema.prisma && npx prisma migrate deploy && npm test"
  after_script:
    # 4. Remove DB
    - docker rm -f test_db || true
    - docker network rm test_net || true
    - rm -rf .npm-cache
  rules:
    #  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"

# --- STAGE: DEPLOY ---
trigger_deploy:
  stage: deploy
  script:
    - |
      curl -X POST "${DOKPLOY_WEBHOOK_URL}" \
      -H "x-gitlab-event: Push Hook" \
      -H "Content-Type: application/json" \
      -d '{"ref": "refs/heads/main"}'
  only:
    - main
