# Express + React (domain.com)
server {
    listen 80;
    server_name ls-monorepo.yukht.dev; 

    # 1. API (Express)
    location /api/ {
        proxy_pass http://express-api:4200/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }


    # 2. Express Redirects (domain.com/*)
    location ~ "^/([a-zA-Z0-9_-]{3,20})$" {

        # If 404 go to location @fallback_to_react
        proxy_intercept_errors on; 
        error_page 404 = @fallback_to_react;

        proxy_pass http://express-api:4200/$1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 3. React SPA 
    location / {
        proxy_pass http://react-spa:80/;
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        proxy_intercept_errors on;
        error_page 404 = /index.html;
    }

    location @fallback_to_react {
        proxy_pass http://react-spa:80;
        proxy_set_header Host $host;
    }
}

    #  Next.js App (next.domain.com)
server {
    listen 80;
    server_name next.ls-monorepo.yukht.dev;
    
    location / {
        proxy_pass http://next-app:3000/;
        proxy_set_header Host $host;
    }

}